### ISSUE TITLE
[黑科技]animation 监听元素插入dom变化

### ISSUE THREAD

**Issue by semi-xi** [semi-xi/blog#21]
在看文章的时候看到的，顺便记录一下
```html
<div id="demo"></div>
```
```css
#demo {
animation-name:demo;
animation-duration: 0.01s;
}
@keyframes demo {
from {
    opacity: 0.99
}
to{
    opacity: 1
}
}
```

然后监听demo的animationstart
