### ISSUE TITLE
自定义有序列表`

### ISSUE THREAD

**Issue by semi-xi** [semi-xi/blog#23]
```css
ol {
margin-left:0px;  
	padding-left:0px;  
	counter-reset:li; 
}
ol > li{
	position:relative;
	margin:0 0 6px 2em;
	list-style:none;
}
ol >li:before{
	content:counter(li);
	counter-increment:li;
	position:absolute;
	color:red;
}
```
